FROM cypress/included:12.12.0

COPY cypress.config.js ./
COPY ./cypress ./cypress

# CMD ["cypress", "run", "--config", "video=false", "--browser", "chrome", "--headed"]
CMD ["bin/bash"]
ENTRYPOINT []
