---
name: Test-Scenario
author: Cedd Burge
version: 1
description: The test scenario is running the cypress tests at the moment

services:
  web:
    build:
      context: "."
      dockerfile: Dockerfile.app
    expose:
      - "3000"
  cypress:
    build:
      context: "."
      dockerfile: Dockerfile.cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000

flow:
  - name: Load 1000
    container: cypress
    commands:
      - type: console
        command: cypress run --config video=false --browser chrome --headless
        detach: true
        note: Running cypress tests against website
        # The cypress docker image has an open issue and writes some stuff to stdErr,
        # which causes a failure even with a 0 exit code
        # https://github.com/cypress-io/cypress-docker-images/issues/747
        ignore-errors: true
