version: 1
name: "Test-Scenario"
author: "Cedd Burge"
description: "The test scenario is running the cypress tests at the moment"

networks:
  cedds-network:

services:
  web:
    build:
      context: "."
      dockerfile: "Dockerfile.app"
    expose:
      - 3000
    networks:
      - cedds-network
  cypress:
    build:
      context: "."
      dockerfile: "Dockerfile.cypress"
    networks:
      - cedds-network
    depends_on:
      - web

flow:
  - name: "Cypress tests"
    commands:
      - note: "Running cypress tests against website"
        type: console
        #        detach: true
        command: "cypress run --config baseUrl=http://web:3000,video=false --browser chrome --headless"
        "ignore-errors": true
    container: cypress
